# Generated by Django 5.1.7 on 2025-03-20 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(blank=True, null=True, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.ImageField(null=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(related_name='movies', to='core.video'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
